/**
 * Elegant sponsor display composer
 * Independent implementation without Sponsorkit
 */

import type { Sponsor, Tier } from '../types';
import { elegantTheme, layoutConfig } from './theme';
import {
  generateDefsSection,
  generateStyleSheet,
  generateGradientBackground,
  generatePatternOverlay,
  generateDecorativeTopBar,
  generateDecorativeBottomBar,
} from './decorations';
import {
  generateTierTitle,
  generateSponsorCard,
  generateTimelineConnector,
  escapeXml,
} from './svg-utils';
import {
  calculateComposedLayout,
  LayoutPosition,
} from './timeline-layout';

/**
 * Elegant composer function
 * Generates SVG from sponsor data
 *
 * @param sponsorsOrTierSponsors Array of sponsors or pre-classified tier sponsors
 * @param tiers Tier configuration
 * @param width SVG width
 */
export function elegantComposer(
  sponsorsOrTierSponsors: Sponsor[] | Array<Array<Sponsor>>,
  tiers: Tier[],
  width: number = 800
): string {

  // Determine tier sponsors array
  let tierSponsors: Array<Array<Sponsor>>;

  if (sponsorsOrTierSponsors.length > 0 && Array.isArray(sponsorsOrTierSponsors[0])) {
    // Already classified
    tierSponsors = sponsorsOrTierSponsors as Array<Array<Sponsor>>;
  } else {
    // Flat sponsor array - classify by tier
    const sponsors = sponsorsOrTierSponsors as Sponsor[];
    tierSponsors = [];
    for (const tier of tiers) {
      const tierMembers = sponsors.filter((sponsor: Sponsor) => {
        return sponsor.tier?.title === tier.title;
      });
      tierSponsors.push(tierMembers);
    }
  }

  // Reverse tiers for display (highest tiers first)
  const reversedTiers = [...tiers].reverse();
  const reversedTierSponsors = [...tierSponsors].reverse();

  // Calculate layout with reversed tiers
  const layout = calculateComposedLayout(reversedTierSponsors);
  const height = layout.canvasHeight;

  // Start SVG generation
  let svg = `<?xml version="1.0" encoding="UTF-8"?>\n`;
  svg += `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">\n`;
  svg += `<!-- Generated by Elegant Sponsor Kit -->\n`;

  // Styles and definitions
  svg += generateStyleSheet(elegantTheme);

  // Generate all clipPath definitions for avatars
  let defsContent = '';
  for (const tierSponsors of reversedTierSponsors) {
    for (const sponsor of tierSponsors) {
      defsContent += `<clipPath id="avatar-clip-${sponsor.login.replace(/[^a-zA-Z0-9-_]/g, '_')}">
        <circle cx="${layoutConfig.avatarRadius}" cy="${layoutConfig.avatarRadius}" r="${layoutConfig.avatarRadius}"/>
      </clipPath>\n`;
    }
  }

  svg += `<defs>\n${defsContent}</defs>\n`;
  svg += generateDefsSection(elegantTheme);

  // Background layer
  svg += `<g class="background-layer">\n`;
  svg += generateGradientBackground(width, height, elegantTheme);
  svg += generatePatternOverlay(width, height);
  svg += generateDecorativeTopBar(width, elegantTheme);
  svg += `</g>\n`;

  // Content layer
  svg += `<g class="content-layer">\n`;

  // Render tiers with sponsors
  let layoutTierIndex = 0;
  for (let i = 0; i < reversedTiers.length; i++) {
    const tier = reversedTiers[i];
    const tierSponsorsData = reversedTierSponsors[i];

    if (tierSponsorsData.length === 0) {
      continue; // Skip tiers without sponsors
    }

    const tierLayout = layout.tiers[layoutTierIndex];
    layoutTierIndex++;

    // Tier group
    svg += `<g class="tier-${i}" data-tier="${tier.title}">\n`;

    // Tier title
    svg += generateTierTitle(
      tierLayout.title.x,
      tierLayout.title.y,
      tier.title,
      elegantTheme
    );

    // Sponsor cards
    for (let i = 0; i < tierSponsorsData.length; i++) {
      const sponsor = tierSponsorsData[i];
      const cardPos = tierLayout.cards[i];
      const profileUrl = escapeXml(sponsor.profile || '#');

      // Wrap with link element
      svg += `<a href="${profileUrl}" target="_blank" rel="noopener noreferrer">\n`;
      svg += generateSponsorCard(cardPos.x, cardPos.y, sponsor, elegantTheme);
      svg += `</a>\n`;
    }

    // Timeline connector (except for last tier)
    if (layoutTierIndex < layout.tiers.length && tierLayout.connectorStartY !== undefined) {
      svg += generateTimelineConnector(
        width / 2,
        tierLayout.connectorStartY,
        layout.tiers[layoutTierIndex].title.y - 30,
        elegantTheme
      );
    }

    svg += `</g>\n`;
  }

  svg += `</g>\n`;

  // Bottom decoration
  svg += generateDecorativeBottomBar(width, height - 5, elegantTheme);

  svg += `</svg>`;

  return svg;
}
